// <auto-generated />
using System;
using System.Runtime.CompilerServices;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Slogs.Data.CompiledModels
{
    public static class CommentRecordUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(CommentRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Author>k__BackingField")]
        public static extern ref string Author(CommentRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AuthorNormalized>k__BackingField")]
        public static extern ref string AuthorNormalized(CommentRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Content>k__BackingField")]
        public static extern ref string Content(CommentRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(CommentRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ParentCommentId>k__BackingField")]
        public static extern ref Guid? ParentCommentId(CommentRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PostId>k__BackingField")]
        public static extern ref Guid PostId(CommentRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAt>k__BackingField")]
        public static extern ref DateTime UpdatedAt(CommentRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Post>k__BackingField")]
        public static extern ref PostRecord Post(CommentRecord @this);
    }
}
