// <auto-generated />
using System;
using System.Runtime.CompilerServices;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Slogs.Data.CompiledModels
{
    public static class FollowRecordUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FollowerUserName>k__BackingField")]
        public static extern ref string FollowerUserName(FollowRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TargetUserName>k__BackingField")]
        public static extern ref string TargetUserName(FollowRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(FollowRecord @this);
    }
}
