// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Slogs.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class FollowRecordEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Slogs.Data.FollowRecord",
                typeof(FollowRecord),
                baseEntityType,
                propertyCount: 3,
                foreignKeyCount: 2,
                unnamedIndexCount: 1,
                keyCount: 1);

            var followerUserName = runtimeEntityType.AddProperty(
                "FollowerUserName",
                typeof(string),
                propertyInfo: typeof(FollowRecord).GetProperty("FollowerUserName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FollowRecord).GetField("<FollowerUserName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 80);
            followerUserName.SetGetter(
                string (FollowRecord instance) => FollowRecordUnsafeAccessors.FollowerUserName(instance),
                bool (FollowRecord instance) => FollowRecordUnsafeAccessors.FollowerUserName(instance) == null);
            followerUserName.SetSetter(
                FollowRecord (FollowRecord instance, string value) =>
                {
                    FollowRecordUnsafeAccessors.FollowerUserName(instance) = value;
                    return instance;
                });
            followerUserName.SetMaterializationSetter(
                FollowRecord (FollowRecord instance, string value) =>
                {
                    FollowRecordUnsafeAccessors.FollowerUserName(instance) = value;
                    return instance;
                });
            followerUserName.SetAccessors(
                string (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<string>(0) : (entry.FlaggedAsTemporary(0) && FollowRecordUnsafeAccessors.FollowerUserName(((FollowRecord)(entry.Entity))) == null ? entry.ReadTemporaryValue<string>(0) : FollowRecordUnsafeAccessors.FollowerUserName(((FollowRecord)(entry.Entity))))),
                string (IInternalEntry entry) => FollowRecordUnsafeAccessors.FollowerUserName(((FollowRecord)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(followerUserName, 0),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(followerUserName, 0));
            followerUserName.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            followerUserName.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "character varying(80)",
                    size: 80));
            followerUserName.TypeMapping = ((NpgsqlStringTypeMapping)followerUserName.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
        followerUserName.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(followerUserName));
        followerUserName.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var targetUserName = runtimeEntityType.AddProperty(
            "TargetUserName",
            typeof(string),
            propertyInfo: typeof(FollowRecord).GetProperty("TargetUserName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(FollowRecord).GetField("<TargetUserName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            afterSaveBehavior: PropertySaveBehavior.Throw,
            maxLength: 80);
        targetUserName.SetGetter(
            string (FollowRecord instance) => FollowRecordUnsafeAccessors.TargetUserName(instance),
            bool (FollowRecord instance) => FollowRecordUnsafeAccessors.TargetUserName(instance) == null);
        targetUserName.SetSetter(
            FollowRecord (FollowRecord instance, string value) =>
            {
                FollowRecordUnsafeAccessors.TargetUserName(instance) = value;
                return instance;
            });
        targetUserName.SetMaterializationSetter(
            FollowRecord (FollowRecord instance, string value) =>
            {
                FollowRecordUnsafeAccessors.TargetUserName(instance) = value;
                return instance;
            });
        targetUserName.SetAccessors(
            string (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<string>(1) : (entry.FlaggedAsTemporary(1) && FollowRecordUnsafeAccessors.TargetUserName(((FollowRecord)(entry.Entity))) == null ? entry.ReadTemporaryValue<string>(1) : FollowRecordUnsafeAccessors.TargetUserName(((FollowRecord)(entry.Entity))))),
            string (IInternalEntry entry) => FollowRecordUnsafeAccessors.TargetUserName(((FollowRecord)(entry.Entity))),
            string (IInternalEntry entry) => entry.ReadOriginalValue<string>(targetUserName, 1),
            string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(targetUserName, 1));
        targetUserName.SetPropertyIndexes(
            index: 1,
            originalValueIndex: 1,
            shadowIndex: -1,
            relationshipIndex: 1,
            storeGenerationIndex: 1);
        targetUserName.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
            comparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            keyComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            providerValueComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "character varying(80)",
                size: 80));
        targetUserName.TypeMapping = ((NpgsqlStringTypeMapping)targetUserName.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
    targetUserName.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(targetUserName));
    targetUserName.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var createdAt = runtimeEntityType.AddProperty(
        "CreatedAt",
        typeof(DateTime),
        propertyInfo: typeof(FollowRecord).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(FollowRecord).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
    createdAt.SetGetter(
        DateTime (FollowRecord instance) => FollowRecordUnsafeAccessors.CreatedAt(instance),
        bool (FollowRecord instance) => FollowRecordUnsafeAccessors.CreatedAt(instance) == default(DateTime));
    createdAt.SetSetter(
        FollowRecord (FollowRecord instance, DateTime value) =>
        {
            FollowRecordUnsafeAccessors.CreatedAt(instance) = value;
            return instance;
        });
    createdAt.SetMaterializationSetter(
        FollowRecord (FollowRecord instance, DateTime value) =>
        {
            FollowRecordUnsafeAccessors.CreatedAt(instance) = value;
            return instance;
        });
    createdAt.SetAccessors(
        DateTime (IInternalEntry entry) => FollowRecordUnsafeAccessors.CreatedAt(((FollowRecord)(entry.Entity))),
        DateTime (IInternalEntry entry) => FollowRecordUnsafeAccessors.CreatedAt(((FollowRecord)(entry.Entity))),
        DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(createdAt, 2),
        DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(createdAt));
    createdAt.SetPropertyIndexes(
        index: 2,
        originalValueIndex: 2,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    createdAt.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
        comparer: new ValueComparer<DateTime>(
            bool (DateTime v1, DateTime v2) => v1.Equals(v2),
            int (DateTime v) => ((object)v).GetHashCode(),
            DateTime (DateTime v) => v),
        keyComparer: new ValueComparer<DateTime>(
            bool (DateTime v1, DateTime v2) => v1.Equals(v2),
            int (DateTime v) => ((object)v).GetHashCode(),
            DateTime (DateTime v) => v),
        providerValueComparer: new ValueComparer<DateTime>(
            bool (DateTime v1, DateTime v2) => v1.Equals(v2),
            int (DateTime v) => ((object)v).GetHashCode(),
            DateTime (DateTime v) => v));
    createdAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var key = runtimeEntityType.AddKey(
        new[] { followerUserName, targetUserName });
    runtimeEntityType.SetPrimaryKey(key);

    var index = runtimeEntityType.AddIndex(
        new[] { targetUserName });

    return runtimeEntityType;
}

public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
{
    var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("FollowerUserName") },
        principalEntityType.FindKey(new[] { principalEntityType.FindProperty("UserName") }),
        principalEntityType,
        deleteBehavior: DeleteBehavior.Cascade,
        required: true);

    return runtimeForeignKey;
}

public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
{
    var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("TargetUserName") },
        principalEntityType.FindKey(new[] { principalEntityType.FindProperty("UserName") }),
        principalEntityType,
        deleteBehavior: DeleteBehavior.Cascade,
        required: true);

    return runtimeForeignKey;
}

public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
{
    var followerUserName = runtimeEntityType.FindProperty("FollowerUserName");
    var targetUserName = runtimeEntityType.FindProperty("TargetUserName");
    var createdAt = runtimeEntityType.FindProperty("CreatedAt");
    var key = runtimeEntityType.FindKey(new[] { followerUserName, targetUserName });
    key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateCompositeFactory(key));
    key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<IReadOnlyList<object>>(key));
    runtimeEntityType.SetOriginalValuesFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((FollowRecord)(source.Entity));
            return ((ISnapshot)(new Snapshot<string, string, DateTime>((source.GetCurrentValue<string>(followerUserName) == null ? null : ((ValueComparer<string>)(((IProperty)followerUserName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(followerUserName))), (source.GetCurrentValue<string>(targetUserName) == null ? null : ((ValueComparer<string>)(((IProperty)targetUserName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(targetUserName))), ((ValueComparer<DateTime>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(createdAt)))));
        });
    runtimeEntityType.SetStoreGeneratedValuesFactory(
        ISnapshot () => ((ISnapshot)(new Snapshot<string, string>((default(string) == null ? null : ((ValueComparer<string>)(((IProperty)followerUserName).GetValueComparer())).Snapshot(default(string))), (default(string) == null ? null : ((ValueComparer<string>)(((IProperty)targetUserName).GetValueComparer())).Snapshot(default(string)))))));
    runtimeEntityType.SetTemporaryValuesFactory(
        ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<string, string>(default(string), default(string)))));
    runtimeEntityType.SetShadowValuesFactory(
        ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
    runtimeEntityType.SetEmptyShadowValuesFactory(
        ISnapshot () => Snapshot.Empty);
    runtimeEntityType.SetRelationshipSnapshotFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((FollowRecord)(source.Entity));
            return ((ISnapshot)(new Snapshot<string, string>((source.GetCurrentValue<string>(followerUserName) == null ? null : ((ValueComparer<string>)(((IProperty)followerUserName).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(followerUserName))), (source.GetCurrentValue<string>(targetUserName) == null ? null : ((ValueComparer<string>)(((IProperty)targetUserName).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(targetUserName))))));
        });
    runtimeEntityType.SetCounts(new PropertyCounts(
        propertyCount: 3,
        navigationCount: 0,
        complexPropertyCount: 0,
        complexCollectionCount: 0,
        originalValueCount: 3,
        shadowCount: 0,
        relationshipCount: 2,
        storeGeneratedCount: 2));
    runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
    runtimeEntityType.AddAnnotation("Relational:Schema", null);
    runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
    runtimeEntityType.AddAnnotation("Relational:TableName", "Follows");
    runtimeEntityType.AddAnnotation("Relational:ViewName", null);
    runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

    Customize(runtimeEntityType);
}

static partial void Customize(RuntimeEntityType runtimeEntityType);
}
}
