// <auto-generated />
using System;
using System.Runtime.CompilerServices;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Slogs.Data.CompiledModels
{
    public static class LlmWikiMcpTokenRecordUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(LlmWikiMcpTokenRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(LlmWikiMcpTokenRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastUsedAt>k__BackingField")]
        public static extern ref DateTime? LastUsedAt(LlmWikiMcpTokenRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(LlmWikiMcpTokenRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OwnerUserName>k__BackingField")]
        public static extern ref string OwnerUserName(LlmWikiMcpTokenRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RevokedAt>k__BackingField")]
        public static extern ref DateTime? RevokedAt(LlmWikiMcpTokenRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TokenHash>k__BackingField")]
        public static extern ref string TokenHash(LlmWikiMcpTokenRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TokenPrefix>k__BackingField")]
        public static extern ref string TokenPrefix(LlmWikiMcpTokenRecord @this);
    }
}
