// <auto-generated />
using System;
using System.Runtime.CompilerServices;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Slogs.Data.CompiledModels
{
    public static class LlmWikiEntryRecordUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(LlmWikiEntryRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AccessCount>k__BackingField")]
        public static extern ref int AccessCount(LlmWikiEntryRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CategoryDepth>k__BackingField")]
        public static extern ref int CategoryDepth(LlmWikiEntryRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CategoryPath>k__BackingField")]
        public static extern ref string CategoryPath(LlmWikiEntryRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Content>k__BackingField")]
        public static extern ref string Content(LlmWikiEntryRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(LlmWikiEntryRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastAccessedAt>k__BackingField")]
        public static extern ref DateTime? LastAccessedAt(LlmWikiEntryRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OwnerUserName>k__BackingField")]
        public static extern ref string OwnerUserName(LlmWikiEntryRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Slug>k__BackingField")]
        public static extern ref string Slug(LlmWikiEntryRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SourcePrompt>k__BackingField")]
        public static extern ref string SourcePrompt(LlmWikiEntryRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Summary>k__BackingField")]
        public static extern ref string Summary(LlmWikiEntryRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TagsJson>k__BackingField")]
        public static extern ref string TagsJson(LlmWikiEntryRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Title>k__BackingField")]
        public static extern ref string Title(LlmWikiEntryRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAt>k__BackingField")]
        public static extern ref DateTime UpdatedAt(LlmWikiEntryRecord @this);
    }
}
