// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Slogs.Data.CompiledModels
{
    public static class PostRecordUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(PostRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Author>k__BackingField")]
        public static extern ref string Author(PostRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Body>k__BackingField")]
        public static extern ref string Body(PostRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BookmarkedByJson>k__BackingField")]
        public static extern ref string BookmarkedByJson(PostRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LikedByJson>k__BackingField")]
        public static extern ref string LikedByJson(PostRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PublishedAt>k__BackingField")]
        public static extern ref DateTime PublishedAt(PostRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ReadTimeMinutes>k__BackingField")]
        public static extern ref int ReadTimeMinutes(PostRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SeriesJson>k__BackingField")]
        public static extern ref string SeriesJson(PostRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Slug>k__BackingField")]
        public static extern ref string Slug(PostRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Summary>k__BackingField")]
        public static extern ref string Summary(PostRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TagsJson>k__BackingField")]
        public static extern ref string TagsJson(PostRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ThumbnailUrl>k__BackingField")]
        public static extern ref string ThumbnailUrl(PostRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Title>k__BackingField")]
        public static extern ref string Title(PostRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAt>k__BackingField")]
        public static extern ref DateTime UpdatedAt(PostRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ViewCount>k__BackingField")]
        public static extern ref int ViewCount(PostRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Comments>k__BackingField")]
        public static extern ref List<CommentRecord> Comments(PostRecord @this);
    }
}
