// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Slogs.Data;
using Slogs.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(SlogsDbContext), typeof(SlogsDbContextModel), ProviderName = "Npgsql.EntityFrameworkCore.PostgreSQL")]
