// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Slogs.Data.CompiledModels
{
    public partial class SlogsDbContextModel
    {
        private SlogsDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("8b55927a-7761-4515-ace7-8665961575e3"), entityTypeCount: 9)
        {
        }

        partial void Initialize()
        {
            var commentRecord = CommentRecordEntityType.Create(this);
            var externalLoginRecord = ExternalLoginRecordEntityType.Create(this);
            var followRecord = FollowRecordEntityType.Create(this);
            var llmWikiEntryRecord = LlmWikiEntryRecordEntityType.Create(this);
            var llmWikiEntrySourceRecord = LlmWikiEntrySourceRecordEntityType.Create(this);
            var llmWikiMcpTokenRecord = LlmWikiMcpTokenRecordEntityType.Create(this);
            var postRecord = PostRecordEntityType.Create(this);
            var postRevisionRecord = PostRevisionRecordEntityType.Create(this);
            var userRecord = UserRecordEntityType.Create(this);

            CommentRecordEntityType.CreateForeignKey1(commentRecord, postRecord);
            ExternalLoginRecordEntityType.CreateForeignKey1(externalLoginRecord, userRecord);
            FollowRecordEntityType.CreateForeignKey1(followRecord, userRecord);
            FollowRecordEntityType.CreateForeignKey2(followRecord, userRecord);
            LlmWikiEntryRecordEntityType.CreateForeignKey1(llmWikiEntryRecord, userRecord);
            LlmWikiEntrySourceRecordEntityType.CreateForeignKey1(llmWikiEntrySourceRecord, llmWikiEntryRecord);
            LlmWikiMcpTokenRecordEntityType.CreateForeignKey1(llmWikiMcpTokenRecord, userRecord);
            PostRevisionRecordEntityType.CreateForeignKey1(postRevisionRecord, postRecord);

            CommentRecordEntityType.CreateAnnotations(commentRecord);
            ExternalLoginRecordEntityType.CreateAnnotations(externalLoginRecord);
            FollowRecordEntityType.CreateAnnotations(followRecord);
            LlmWikiEntryRecordEntityType.CreateAnnotations(llmWikiEntryRecord);
            LlmWikiEntrySourceRecordEntityType.CreateAnnotations(llmWikiEntrySourceRecord);
            LlmWikiMcpTokenRecordEntityType.CreateAnnotations(llmWikiMcpTokenRecord);
            PostRecordEntityType.CreateAnnotations(postRecord);
            PostRevisionRecordEntityType.CreateAnnotations(postRevisionRecord);
            UserRecordEntityType.CreateAnnotations(userRecord);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "11.0.0-preview.4.26230.115");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
