// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Update.Internal;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Slogs.Data.CompiledModels
{
    public partial class SlogsDbContextModel
    {
        private SlogsDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("39cee142-59f4-4950-b5e1-3a6d8e5fe684"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var commentRecord = CommentRecordEntityType.Create(this);
            var followRecord = FollowRecordEntityType.Create(this);
            var postRecord = PostRecordEntityType.Create(this);
            var userRecord = UserRecordEntityType.Create(this);

            CommentRecordEntityType.CreateForeignKey1(commentRecord, postRecord);
            FollowRecordEntityType.CreateForeignKey1(followRecord, userRecord);
            FollowRecordEntityType.CreateForeignKey2(followRecord, userRecord);

            CommentRecordEntityType.CreateAnnotations(commentRecord);
            FollowRecordEntityType.CreateAnnotations(followRecord);
            PostRecordEntityType.CreateAnnotations(postRecord);
            UserRecordEntityType.CreateAnnotations(userRecord);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "11.0.0-preview.4.26230.115");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var commentRecord = FindEntityType("Slogs.Data.CommentRecord")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            commentRecord.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var slogsDataCommentRecordTableBase = new TableBase("Slogs.Data.CommentRecord", null, relationalModel);
            var authorColumnBase = new ColumnBase<ColumnMappingBase>("Author", "character varying(80)", slogsDataCommentRecordTableBase);
            slogsDataCommentRecordTableBase.Columns.Add("Author", authorColumnBase);
            var authorNormalizedColumnBase = new ColumnBase<ColumnMappingBase>("AuthorNormalized", "character varying(80)", slogsDataCommentRecordTableBase);
            slogsDataCommentRecordTableBase.Columns.Add("AuthorNormalized", authorNormalizedColumnBase);
            var contentColumnBase = new ColumnBase<ColumnMappingBase>("Content", "character varying(1000)", slogsDataCommentRecordTableBase);
            slogsDataCommentRecordTableBase.Columns.Add("Content", contentColumnBase);
            var createdAtColumnBase = new ColumnBase<ColumnMappingBase>("CreatedAt", "timestamp with time zone", slogsDataCommentRecordTableBase);
            slogsDataCommentRecordTableBase.Columns.Add("CreatedAt", createdAtColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "uuid", slogsDataCommentRecordTableBase);
            slogsDataCommentRecordTableBase.Columns.Add("Id", idColumnBase);
            var parentCommentIdColumnBase = new ColumnBase<ColumnMappingBase>("ParentCommentId", "uuid", slogsDataCommentRecordTableBase)
            {
                IsNullable = true
            };
            slogsDataCommentRecordTableBase.Columns.Add("ParentCommentId", parentCommentIdColumnBase);
            var postIdColumnBase = new ColumnBase<ColumnMappingBase>("PostId", "uuid", slogsDataCommentRecordTableBase);
            slogsDataCommentRecordTableBase.Columns.Add("PostId", postIdColumnBase);
            var updatedAtColumnBase = new ColumnBase<ColumnMappingBase>("UpdatedAt", "timestamp with time zone", slogsDataCommentRecordTableBase);
            slogsDataCommentRecordTableBase.Columns.Add("UpdatedAt", updatedAtColumnBase);
            relationalModel.DefaultTables.Add("Slogs.Data.CommentRecord", slogsDataCommentRecordTableBase);
            var slogsDataCommentRecordMappingBase = new TableMappingBase<ColumnMappingBase>(commentRecord, slogsDataCommentRecordTableBase, null);
            slogsDataCommentRecordTableBase.AddTypeMapping(slogsDataCommentRecordMappingBase, false);
            defaultTableMappings.Add(slogsDataCommentRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, commentRecord.FindProperty("Id")!, slogsDataCommentRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)authorColumnBase, commentRecord.FindProperty("Author")!, slogsDataCommentRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)authorNormalizedColumnBase, commentRecord.FindProperty("AuthorNormalized")!, slogsDataCommentRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)contentColumnBase, commentRecord.FindProperty("Content")!, slogsDataCommentRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase, commentRecord.FindProperty("CreatedAt")!, slogsDataCommentRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)parentCommentIdColumnBase, commentRecord.FindProperty("ParentCommentId")!, slogsDataCommentRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)postIdColumnBase, commentRecord.FindProperty("PostId")!, slogsDataCommentRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtColumnBase, commentRecord.FindProperty("UpdatedAt")!, slogsDataCommentRecordMappingBase);

            var tableMappings = new List<TableMapping>();
            commentRecord.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var commentsTable = new Table("Comments", null, relationalModel);
            var idColumn = new Column("Id", "uuid", commentsTable);
            commentsTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn);
            var authorColumn = new Column("Author", "character varying(80)", commentsTable);
            commentsTable.Columns.Add("Author", authorColumn);
            authorColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(authorColumn);
            var authorNormalizedColumn = new Column("AuthorNormalized", "character varying(80)", commentsTable);
            commentsTable.Columns.Add("AuthorNormalized", authorNormalizedColumn);
            authorNormalizedColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(authorNormalizedColumn);
            var contentColumn = new Column("Content", "character varying(1000)", commentsTable);
            commentsTable.Columns.Add("Content", contentColumn);
            contentColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(contentColumn);
            var createdAtColumn = new Column("CreatedAt", "timestamp with time zone", commentsTable);
            commentsTable.Columns.Add("CreatedAt", createdAtColumn);
            createdAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(createdAtColumn);
            var parentCommentIdColumn = new Column("ParentCommentId", "uuid", commentsTable)
            {
                IsNullable = true
            };
            commentsTable.Columns.Add("ParentCommentId", parentCommentIdColumn);
            parentCommentIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(parentCommentIdColumn);
            var postIdColumn = new Column("PostId", "uuid", commentsTable);
            commentsTable.Columns.Add("PostId", postIdColumn);
            postIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(postIdColumn);
            var updatedAtColumn = new Column("UpdatedAt", "timestamp with time zone", commentsTable);
            commentsTable.Columns.Add("UpdatedAt", updatedAtColumn);
            updatedAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(updatedAtColumn);
            relationalModel.Tables.Add(("Comments", null), commentsTable);
            var commentsTableMapping = new TableMapping(commentRecord, commentsTable, null);
            commentsTable.AddTypeMapping(commentsTableMapping, false);
            tableMappings.Add(commentsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, commentRecord.FindProperty("Id")!, commentsTableMapping);
            RelationalModel.CreateColumnMapping(authorColumn, commentRecord.FindProperty("Author")!, commentsTableMapping);
            RelationalModel.CreateColumnMapping(authorNormalizedColumn, commentRecord.FindProperty("AuthorNormalized")!, commentsTableMapping);
            RelationalModel.CreateColumnMapping(contentColumn, commentRecord.FindProperty("Content")!, commentsTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn, commentRecord.FindProperty("CreatedAt")!, commentsTableMapping);
            RelationalModel.CreateColumnMapping(parentCommentIdColumn, commentRecord.FindProperty("ParentCommentId")!, commentsTableMapping);
            RelationalModel.CreateColumnMapping(postIdColumn, commentRecord.FindProperty("PostId")!, commentsTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtColumn, commentRecord.FindProperty("UpdatedAt")!, commentsTableMapping);
            var pK_Comments = new UniqueConstraint("PK_Comments", commentsTable, new[] { idColumn });
            commentsTable.PrimaryKey = pK_Comments;
            pK_Comments.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_Comments));
            var pK_CommentsKey = RelationalModel.GetKey(this,
                "Slogs.Data.CommentRecord",
                new[] { "Id" });
            pK_Comments.MappedKeys.Add(pK_CommentsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_CommentsKey).Add(pK_Comments);
            commentsTable.UniqueConstraints.Add("PK_Comments", pK_Comments);
            var iX_Comments_ParentCommentId = new TableIndex(
            "IX_Comments_ParentCommentId", commentsTable, new[] { parentCommentIdColumn }, false);
            iX_Comments_ParentCommentId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<Guid>(iX_Comments_ParentCommentId));
            var iX_Comments_ParentCommentIdIx = RelationalModel.GetIndex(this,
                "Slogs.Data.CommentRecord",
                new[] { "ParentCommentId" });
            iX_Comments_ParentCommentId.MappedIndexes.Add(iX_Comments_ParentCommentIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Comments_ParentCommentIdIx).Add(iX_Comments_ParentCommentId);
            commentsTable.Indexes.Add("IX_Comments_ParentCommentId", iX_Comments_ParentCommentId);
            var iX_Comments_PostId = new TableIndex(
            "IX_Comments_PostId", commentsTable, new[] { postIdColumn }, false);
            iX_Comments_PostId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<Guid>(iX_Comments_PostId));
            var iX_Comments_PostIdIx = RelationalModel.GetIndex(this,
                "Slogs.Data.CommentRecord",
                new[] { "PostId" });
            iX_Comments_PostId.MappedIndexes.Add(iX_Comments_PostIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Comments_PostIdIx).Add(iX_Comments_PostId);
            commentsTable.Indexes.Add("IX_Comments_PostId", iX_Comments_PostId);

            var followRecord = FindEntityType("Slogs.Data.FollowRecord")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            followRecord.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var slogsDataFollowRecordTableBase = new TableBase("Slogs.Data.FollowRecord", null, relationalModel);
            var createdAtColumnBase0 = new ColumnBase<ColumnMappingBase>("CreatedAt", "timestamp with time zone", slogsDataFollowRecordTableBase);
            slogsDataFollowRecordTableBase.Columns.Add("CreatedAt", createdAtColumnBase0);
            var followerUserNameColumnBase = new ColumnBase<ColumnMappingBase>("FollowerUserName", "character varying(80)", slogsDataFollowRecordTableBase);
            slogsDataFollowRecordTableBase.Columns.Add("FollowerUserName", followerUserNameColumnBase);
            var targetUserNameColumnBase = new ColumnBase<ColumnMappingBase>("TargetUserName", "character varying(80)", slogsDataFollowRecordTableBase);
            slogsDataFollowRecordTableBase.Columns.Add("TargetUserName", targetUserNameColumnBase);
            relationalModel.DefaultTables.Add("Slogs.Data.FollowRecord", slogsDataFollowRecordTableBase);
            var slogsDataFollowRecordMappingBase = new TableMappingBase<ColumnMappingBase>(followRecord, slogsDataFollowRecordTableBase, null);
            slogsDataFollowRecordTableBase.AddTypeMapping(slogsDataFollowRecordMappingBase, false);
            defaultTableMappings0.Add(slogsDataFollowRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)followerUserNameColumnBase, followRecord.FindProperty("FollowerUserName")!, slogsDataFollowRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)targetUserNameColumnBase, followRecord.FindProperty("TargetUserName")!, slogsDataFollowRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase0, followRecord.FindProperty("CreatedAt")!, slogsDataFollowRecordMappingBase);

            var tableMappings0 = new List<TableMapping>();
            followRecord.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var followsTable = new Table("Follows", null, relationalModel);
            var followerUserNameColumn = new Column("FollowerUserName", "character varying(80)", followsTable);
            followsTable.Columns.Add("FollowerUserName", followerUserNameColumn);
            followerUserNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(followerUserNameColumn);
            var targetUserNameColumn = new Column("TargetUserName", "character varying(80)", followsTable);
            followsTable.Columns.Add("TargetUserName", targetUserNameColumn);
            targetUserNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(targetUserNameColumn);
            var createdAtColumn0 = new Column("CreatedAt", "timestamp with time zone", followsTable);
            followsTable.Columns.Add("CreatedAt", createdAtColumn0);
            createdAtColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(createdAtColumn0);
            relationalModel.Tables.Add(("Follows", null), followsTable);
            var followsTableMapping = new TableMapping(followRecord, followsTable, null);
            followsTable.AddTypeMapping(followsTableMapping, false);
            tableMappings0.Add(followsTableMapping);
            RelationalModel.CreateColumnMapping(followerUserNameColumn, followRecord.FindProperty("FollowerUserName")!, followsTableMapping);
            RelationalModel.CreateColumnMapping(targetUserNameColumn, followRecord.FindProperty("TargetUserName")!, followsTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn0, followRecord.FindProperty("CreatedAt")!, followsTableMapping);
            var pK_Follows = new UniqueConstraint("PK_Follows", followsTable, new[] { followerUserNameColumn, targetUserNameColumn });
            followsTable.PrimaryKey = pK_Follows;
            pK_Follows.SetRowKeyValueFactory(new CompositeRowKeyValueFactory(pK_Follows));
            var pK_FollowsKey = RelationalModel.GetKey(this,
                "Slogs.Data.FollowRecord",
                new[] { "FollowerUserName", "TargetUserName" });
            pK_Follows.MappedKeys.Add(pK_FollowsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_FollowsKey).Add(pK_Follows);
            followsTable.UniqueConstraints.Add("PK_Follows", pK_Follows);
            var iX_Follows_TargetUserName = new TableIndex(
            "IX_Follows_TargetUserName", followsTable, new[] { targetUserNameColumn }, false);
            iX_Follows_TargetUserName.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_Follows_TargetUserName));
            var iX_Follows_TargetUserNameIx = RelationalModel.GetIndex(this,
                "Slogs.Data.FollowRecord",
                new[] { "TargetUserName" });
            iX_Follows_TargetUserName.MappedIndexes.Add(iX_Follows_TargetUserNameIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Follows_TargetUserNameIx).Add(iX_Follows_TargetUserName);
            followsTable.Indexes.Add("IX_Follows_TargetUserName", iX_Follows_TargetUserName);

            var postRecord = FindEntityType("Slogs.Data.PostRecord")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            postRecord.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var slogsDataPostRecordTableBase = new TableBase("Slogs.Data.PostRecord", null, relationalModel);
            var authorColumnBase0 = new ColumnBase<ColumnMappingBase>("Author", "character varying(80)", slogsDataPostRecordTableBase);
            slogsDataPostRecordTableBase.Columns.Add("Author", authorColumnBase0);
            var bodyColumnBase = new ColumnBase<ColumnMappingBase>("Body", "text", slogsDataPostRecordTableBase);
            slogsDataPostRecordTableBase.Columns.Add("Body", bodyColumnBase);
            var bookmarkedByJsonColumnBase = new ColumnBase<ColumnMappingBase>("BookmarkedByJson", "jsonb", slogsDataPostRecordTableBase);
            slogsDataPostRecordTableBase.Columns.Add("BookmarkedByJson", bookmarkedByJsonColumnBase);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("Id", "uuid", slogsDataPostRecordTableBase);
            slogsDataPostRecordTableBase.Columns.Add("Id", idColumnBase0);
            var likedByJsonColumnBase = new ColumnBase<ColumnMappingBase>("LikedByJson", "jsonb", slogsDataPostRecordTableBase);
            slogsDataPostRecordTableBase.Columns.Add("LikedByJson", likedByJsonColumnBase);
            var publishedAtColumnBase = new ColumnBase<ColumnMappingBase>("PublishedAt", "timestamp with time zone", slogsDataPostRecordTableBase);
            slogsDataPostRecordTableBase.Columns.Add("PublishedAt", publishedAtColumnBase);
            var readTimeMinutesColumnBase = new ColumnBase<ColumnMappingBase>("ReadTimeMinutes", "integer", slogsDataPostRecordTableBase);
            slogsDataPostRecordTableBase.Columns.Add("ReadTimeMinutes", readTimeMinutesColumnBase);
            var seriesJsonColumnBase = new ColumnBase<ColumnMappingBase>("SeriesJson", "jsonb", slogsDataPostRecordTableBase);
            slogsDataPostRecordTableBase.Columns.Add("SeriesJson", seriesJsonColumnBase);
            var slugColumnBase = new ColumnBase<ColumnMappingBase>("Slug", "character varying(220)", slogsDataPostRecordTableBase);
            slogsDataPostRecordTableBase.Columns.Add("Slug", slugColumnBase);
            var summaryColumnBase = new ColumnBase<ColumnMappingBase>("Summary", "character varying(500)", slogsDataPostRecordTableBase);
            slogsDataPostRecordTableBase.Columns.Add("Summary", summaryColumnBase);
            var tagsJsonColumnBase = new ColumnBase<ColumnMappingBase>("TagsJson", "jsonb", slogsDataPostRecordTableBase);
            slogsDataPostRecordTableBase.Columns.Add("TagsJson", tagsJsonColumnBase);
            var thumbnailUrlColumnBase = new ColumnBase<ColumnMappingBase>("ThumbnailUrl", "character varying(500)", slogsDataPostRecordTableBase);
            slogsDataPostRecordTableBase.Columns.Add("ThumbnailUrl", thumbnailUrlColumnBase);
            var titleColumnBase = new ColumnBase<ColumnMappingBase>("Title", "character varying(200)", slogsDataPostRecordTableBase);
            slogsDataPostRecordTableBase.Columns.Add("Title", titleColumnBase);
            var updatedAtColumnBase0 = new ColumnBase<ColumnMappingBase>("UpdatedAt", "timestamp with time zone", slogsDataPostRecordTableBase);
            slogsDataPostRecordTableBase.Columns.Add("UpdatedAt", updatedAtColumnBase0);
            var viewCountColumnBase = new ColumnBase<ColumnMappingBase>("ViewCount", "integer", slogsDataPostRecordTableBase);
            slogsDataPostRecordTableBase.Columns.Add("ViewCount", viewCountColumnBase);
            relationalModel.DefaultTables.Add("Slogs.Data.PostRecord", slogsDataPostRecordTableBase);
            var slogsDataPostRecordMappingBase = new TableMappingBase<ColumnMappingBase>(postRecord, slogsDataPostRecordTableBase, null);
            slogsDataPostRecordTableBase.AddTypeMapping(slogsDataPostRecordMappingBase, false);
            defaultTableMappings1.Add(slogsDataPostRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, postRecord.FindProperty("Id")!, slogsDataPostRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)authorColumnBase0, postRecord.FindProperty("Author")!, slogsDataPostRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)bodyColumnBase, postRecord.FindProperty("Body")!, slogsDataPostRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)bookmarkedByJsonColumnBase, postRecord.FindProperty("BookmarkedByJson")!, slogsDataPostRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)likedByJsonColumnBase, postRecord.FindProperty("LikedByJson")!, slogsDataPostRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)publishedAtColumnBase, postRecord.FindProperty("PublishedAt")!, slogsDataPostRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)readTimeMinutesColumnBase, postRecord.FindProperty("ReadTimeMinutes")!, slogsDataPostRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)seriesJsonColumnBase, postRecord.FindProperty("SeriesJson")!, slogsDataPostRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)slugColumnBase, postRecord.FindProperty("Slug")!, slogsDataPostRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)summaryColumnBase, postRecord.FindProperty("Summary")!, slogsDataPostRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)tagsJsonColumnBase, postRecord.FindProperty("TagsJson")!, slogsDataPostRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)thumbnailUrlColumnBase, postRecord.FindProperty("ThumbnailUrl")!, slogsDataPostRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)titleColumnBase, postRecord.FindProperty("Title")!, slogsDataPostRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtColumnBase0, postRecord.FindProperty("UpdatedAt")!, slogsDataPostRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)viewCountColumnBase, postRecord.FindProperty("ViewCount")!, slogsDataPostRecordMappingBase);

            var tableMappings1 = new List<TableMapping>();
            postRecord.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var postsTable = new Table("Posts", null, relationalModel);
            var idColumn0 = new Column("Id", "uuid", postsTable);
            postsTable.Columns.Add("Id", idColumn0);
            idColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn0);
            var authorColumn0 = new Column("Author", "character varying(80)", postsTable);
            postsTable.Columns.Add("Author", authorColumn0);
            authorColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(authorColumn0);
            var bodyColumn = new Column("Body", "text", postsTable);
            postsTable.Columns.Add("Body", bodyColumn);
            bodyColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(bodyColumn);
            var bookmarkedByJsonColumn = new Column("BookmarkedByJson", "jsonb", postsTable);
            postsTable.Columns.Add("BookmarkedByJson", bookmarkedByJsonColumn);
            bookmarkedByJsonColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(bookmarkedByJsonColumn);
            var likedByJsonColumn = new Column("LikedByJson", "jsonb", postsTable);
            postsTable.Columns.Add("LikedByJson", likedByJsonColumn);
            likedByJsonColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(likedByJsonColumn);
            var publishedAtColumn = new Column("PublishedAt", "timestamp with time zone", postsTable);
            postsTable.Columns.Add("PublishedAt", publishedAtColumn);
            publishedAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(publishedAtColumn);
            var readTimeMinutesColumn = new Column("ReadTimeMinutes", "integer", postsTable);
            postsTable.Columns.Add("ReadTimeMinutes", readTimeMinutesColumn);
            readTimeMinutesColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(readTimeMinutesColumn);
            var seriesJsonColumn = new Column("SeriesJson", "jsonb", postsTable);
            postsTable.Columns.Add("SeriesJson", seriesJsonColumn);
            seriesJsonColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(seriesJsonColumn);
            var slugColumn = new Column("Slug", "character varying(220)", postsTable);
            postsTable.Columns.Add("Slug", slugColumn);
            slugColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(slugColumn);
            var summaryColumn = new Column("Summary", "character varying(500)", postsTable);
            postsTable.Columns.Add("Summary", summaryColumn);
            summaryColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(summaryColumn);
            var tagsJsonColumn = new Column("TagsJson", "jsonb", postsTable);
            postsTable.Columns.Add("TagsJson", tagsJsonColumn);
            tagsJsonColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(tagsJsonColumn);
            var thumbnailUrlColumn = new Column("ThumbnailUrl", "character varying(500)", postsTable);
            postsTable.Columns.Add("ThumbnailUrl", thumbnailUrlColumn);
            thumbnailUrlColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(thumbnailUrlColumn);
            var titleColumn = new Column("Title", "character varying(200)", postsTable);
            postsTable.Columns.Add("Title", titleColumn);
            titleColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(titleColumn);
            var updatedAtColumn0 = new Column("UpdatedAt", "timestamp with time zone", postsTable);
            postsTable.Columns.Add("UpdatedAt", updatedAtColumn0);
            updatedAtColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(updatedAtColumn0);
            var viewCountColumn = new Column("ViewCount", "integer", postsTable);
            postsTable.Columns.Add("ViewCount", viewCountColumn);
            viewCountColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(viewCountColumn);
            relationalModel.Tables.Add(("Posts", null), postsTable);
            var postsTableMapping = new TableMapping(postRecord, postsTable, null);
            postsTable.AddTypeMapping(postsTableMapping, false);
            tableMappings1.Add(postsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, postRecord.FindProperty("Id")!, postsTableMapping);
            RelationalModel.CreateColumnMapping(authorColumn0, postRecord.FindProperty("Author")!, postsTableMapping);
            RelationalModel.CreateColumnMapping(bodyColumn, postRecord.FindProperty("Body")!, postsTableMapping);
            RelationalModel.CreateColumnMapping(bookmarkedByJsonColumn, postRecord.FindProperty("BookmarkedByJson")!, postsTableMapping);
            RelationalModel.CreateColumnMapping(likedByJsonColumn, postRecord.FindProperty("LikedByJson")!, postsTableMapping);
            RelationalModel.CreateColumnMapping(publishedAtColumn, postRecord.FindProperty("PublishedAt")!, postsTableMapping);
            RelationalModel.CreateColumnMapping(readTimeMinutesColumn, postRecord.FindProperty("ReadTimeMinutes")!, postsTableMapping);
            RelationalModel.CreateColumnMapping(seriesJsonColumn, postRecord.FindProperty("SeriesJson")!, postsTableMapping);
            RelationalModel.CreateColumnMapping(slugColumn, postRecord.FindProperty("Slug")!, postsTableMapping);
            RelationalModel.CreateColumnMapping(summaryColumn, postRecord.FindProperty("Summary")!, postsTableMapping);
            RelationalModel.CreateColumnMapping(tagsJsonColumn, postRecord.FindProperty("TagsJson")!, postsTableMapping);
            RelationalModel.CreateColumnMapping(thumbnailUrlColumn, postRecord.FindProperty("ThumbnailUrl")!, postsTableMapping);
            RelationalModel.CreateColumnMapping(titleColumn, postRecord.FindProperty("Title")!, postsTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtColumn0, postRecord.FindProperty("UpdatedAt")!, postsTableMapping);
            RelationalModel.CreateColumnMapping(viewCountColumn, postRecord.FindProperty("ViewCount")!, postsTableMapping);
            var pK_Posts = new UniqueConstraint("PK_Posts", postsTable, new[] { idColumn0 });
            postsTable.PrimaryKey = pK_Posts;
            pK_Posts.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_Posts));
            var pK_PostsKey = RelationalModel.GetKey(this,
                "Slogs.Data.PostRecord",
                new[] { "Id" });
            pK_Posts.MappedKeys.Add(pK_PostsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_PostsKey).Add(pK_Posts);
            postsTable.UniqueConstraints.Add("PK_Posts", pK_Posts);
            var iX_Posts_Author = new TableIndex(
            "IX_Posts_Author", postsTable, new[] { authorColumn0 }, false);
            iX_Posts_Author.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_Posts_Author));
            var iX_Posts_AuthorIx = RelationalModel.GetIndex(this,
                "Slogs.Data.PostRecord",
                new[] { "Author" });
            iX_Posts_Author.MappedIndexes.Add(iX_Posts_AuthorIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Posts_AuthorIx).Add(iX_Posts_Author);
            postsTable.Indexes.Add("IX_Posts_Author", iX_Posts_Author);
            var iX_Posts_Slug = new TableIndex(
            "IX_Posts_Slug", postsTable, new[] { slugColumn }, true);
            iX_Posts_Slug.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_Posts_Slug));
            var iX_Posts_SlugIx = RelationalModel.GetIndex(this,
                "Slogs.Data.PostRecord",
                new[] { "Slug" });
            iX_Posts_Slug.MappedIndexes.Add(iX_Posts_SlugIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Posts_SlugIx).Add(iX_Posts_Slug);
            postsTable.Indexes.Add("IX_Posts_Slug", iX_Posts_Slug);

            var userRecord = FindEntityType("Slogs.Data.UserRecord")!;

            var defaultTableMappings2 = new List<TableMappingBase<ColumnMappingBase>>();
            userRecord.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings2);
            var slogsDataUserRecordTableBase = new TableBase("Slogs.Data.UserRecord", null, relationalModel);
            var bioColumnBase = new ColumnBase<ColumnMappingBase>("Bio", "character varying(280)", slogsDataUserRecordTableBase);
            slogsDataUserRecordTableBase.Columns.Add("Bio", bioColumnBase);
            var displayNameColumnBase = new ColumnBase<ColumnMappingBase>("DisplayName", "character varying(80)", slogsDataUserRecordTableBase);
            slogsDataUserRecordTableBase.Columns.Add("DisplayName", displayNameColumnBase);
            var passwordColumnBase = new ColumnBase<ColumnMappingBase>("Password", "character varying(200)", slogsDataUserRecordTableBase);
            slogsDataUserRecordTableBase.Columns.Add("Password", passwordColumnBase);
            var profileImageUrlColumnBase = new ColumnBase<ColumnMappingBase>("ProfileImageUrl", "character varying(500)", slogsDataUserRecordTableBase);
            slogsDataUserRecordTableBase.Columns.Add("ProfileImageUrl", profileImageUrlColumnBase);
            var registeredAtColumnBase = new ColumnBase<ColumnMappingBase>("RegisteredAt", "timestamp with time zone", slogsDataUserRecordTableBase);
            slogsDataUserRecordTableBase.Columns.Add("RegisteredAt", registeredAtColumnBase);
            var userNameColumnBase = new ColumnBase<ColumnMappingBase>("UserName", "character varying(80)", slogsDataUserRecordTableBase);
            slogsDataUserRecordTableBase.Columns.Add("UserName", userNameColumnBase);
            relationalModel.DefaultTables.Add("Slogs.Data.UserRecord", slogsDataUserRecordTableBase);
            var slogsDataUserRecordMappingBase = new TableMappingBase<ColumnMappingBase>(userRecord, slogsDataUserRecordTableBase, null);
            slogsDataUserRecordTableBase.AddTypeMapping(slogsDataUserRecordMappingBase, false);
            defaultTableMappings2.Add(slogsDataUserRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userNameColumnBase, userRecord.FindProperty("UserName")!, slogsDataUserRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)bioColumnBase, userRecord.FindProperty("Bio")!, slogsDataUserRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)displayNameColumnBase, userRecord.FindProperty("DisplayName")!, slogsDataUserRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)passwordColumnBase, userRecord.FindProperty("Password")!, slogsDataUserRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)profileImageUrlColumnBase, userRecord.FindProperty("ProfileImageUrl")!, slogsDataUserRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)registeredAtColumnBase, userRecord.FindProperty("RegisteredAt")!, slogsDataUserRecordMappingBase);

            var tableMappings2 = new List<TableMapping>();
            userRecord.SetRuntimeAnnotation("Relational:TableMappings", tableMappings2);
            var usersTable = new Table("Users", null, relationalModel);
            var userNameColumn = new Column("UserName", "character varying(80)", usersTable);
            usersTable.Columns.Add("UserName", userNameColumn);
            userNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(userNameColumn);
            var bioColumn = new Column("Bio", "character varying(280)", usersTable);
            usersTable.Columns.Add("Bio", bioColumn);
            bioColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(bioColumn);
            var displayNameColumn = new Column("DisplayName", "character varying(80)", usersTable);
            usersTable.Columns.Add("DisplayName", displayNameColumn);
            displayNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(displayNameColumn);
            var passwordColumn = new Column("Password", "character varying(200)", usersTable);
            usersTable.Columns.Add("Password", passwordColumn);
            passwordColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(passwordColumn);
            var profileImageUrlColumn = new Column("ProfileImageUrl", "character varying(500)", usersTable);
            usersTable.Columns.Add("ProfileImageUrl", profileImageUrlColumn);
            profileImageUrlColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(profileImageUrlColumn);
            var registeredAtColumn = new Column("RegisteredAt", "timestamp with time zone", usersTable);
            usersTable.Columns.Add("RegisteredAt", registeredAtColumn);
            registeredAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(registeredAtColumn);
            relationalModel.Tables.Add(("Users", null), usersTable);
            var usersTableMapping = new TableMapping(userRecord, usersTable, null);
            usersTable.AddTypeMapping(usersTableMapping, false);
            tableMappings2.Add(usersTableMapping);
            RelationalModel.CreateColumnMapping(userNameColumn, userRecord.FindProperty("UserName")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(bioColumn, userRecord.FindProperty("Bio")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(displayNameColumn, userRecord.FindProperty("DisplayName")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(passwordColumn, userRecord.FindProperty("Password")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(profileImageUrlColumn, userRecord.FindProperty("ProfileImageUrl")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(registeredAtColumn, userRecord.FindProperty("RegisteredAt")!, usersTableMapping);
            var pK_Users = new UniqueConstraint("PK_Users", usersTable, new[] { userNameColumn });
            usersTable.PrimaryKey = pK_Users;
            pK_Users.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<string>(pK_Users));
            var pK_UsersKey = RelationalModel.GetKey(this,
                "Slogs.Data.UserRecord",
                new[] { "UserName" });
            pK_Users.MappedKeys.Add(pK_UsersKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_UsersKey).Add(pK_Users);
            usersTable.UniqueConstraints.Add("PK_Users", pK_Users);
            var fK_Comments_Posts_PostId = new ForeignKeyConstraint(
                "FK_Comments_Posts_PostId", commentsTable, postsTable,
                new[] { postIdColumn },
                postsTable.FindUniqueConstraint("PK_Posts")!, ReferentialAction.Cascade);
            fK_Comments_Posts_PostId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid, Guid>(fK_Comments_Posts_PostId));
            var fK_Comments_Posts_PostIdFk = RelationalModel.GetForeignKey(this,
                "Slogs.Data.CommentRecord",
                new[] { "PostId" },
                "Slogs.Data.PostRecord",
                new[] { "Id" });
            fK_Comments_Posts_PostId.MappedForeignKeys.Add(fK_Comments_Posts_PostIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Comments_Posts_PostIdFk).Add(fK_Comments_Posts_PostId);
            commentsTable.ForeignKeyConstraints.Add(fK_Comments_Posts_PostId);
            postsTable.ReferencingForeignKeyConstraints.Add(fK_Comments_Posts_PostId);
            var fK_Follows_Users_FollowerUserName = new ForeignKeyConstraint(
                "FK_Follows_Users_FollowerUserName", followsTable, usersTable,
                new[] { followerUserNameColumn },
                usersTable.FindUniqueConstraint("PK_Users")!, ReferentialAction.Cascade);
            fK_Follows_Users_FollowerUserName.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNullableFactory<string, string>(fK_Follows_Users_FollowerUserName));
            var fK_Follows_Users_FollowerUserNameFk = RelationalModel.GetForeignKey(this,
                "Slogs.Data.FollowRecord",
                new[] { "FollowerUserName" },
                "Slogs.Data.UserRecord",
                new[] { "UserName" });
            fK_Follows_Users_FollowerUserName.MappedForeignKeys.Add(fK_Follows_Users_FollowerUserNameFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Follows_Users_FollowerUserNameFk).Add(fK_Follows_Users_FollowerUserName);
            followsTable.ForeignKeyConstraints.Add(fK_Follows_Users_FollowerUserName);
            usersTable.ReferencingForeignKeyConstraints.Add(fK_Follows_Users_FollowerUserName);
            var fK_Follows_Users_TargetUserName = new ForeignKeyConstraint(
                "FK_Follows_Users_TargetUserName", followsTable, usersTable,
                new[] { targetUserNameColumn },
                usersTable.FindUniqueConstraint("PK_Users")!, ReferentialAction.Cascade);
            fK_Follows_Users_TargetUserName.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNullableFactory<string, string>(fK_Follows_Users_TargetUserName));
            var fK_Follows_Users_TargetUserNameFk = RelationalModel.GetForeignKey(this,
                "Slogs.Data.FollowRecord",
                new[] { "TargetUserName" },
                "Slogs.Data.UserRecord",
                new[] { "UserName" });
            fK_Follows_Users_TargetUserName.MappedForeignKeys.Add(fK_Follows_Users_TargetUserNameFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Follows_Users_TargetUserNameFk).Add(fK_Follows_Users_TargetUserName);
            followsTable.ForeignKeyConstraints.Add(fK_Follows_Users_TargetUserName);
            usersTable.ReferencingForeignKeyConstraints.Add(fK_Follows_Users_TargetUserName);
            return relationalModel.MakeReadOnly();
        }
    }
}
