// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Slogs.Data.CompiledModels
{
    public partial class SlogsDbContextModel
    {
        private SlogsDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("02945d43-d6d9-4072-874f-3eec924b3384"), entityTypeCount: 13)
        {
        }

        partial void Initialize()
        {
            var commentRecord = CommentRecordEntityType.Create(this);
            var externalLoginRecord = ExternalLoginRecordEntityType.Create(this);
            var followRecord = FollowRecordEntityType.Create(this);
            var llmWikiEntryRecord = LlmWikiEntryRecordEntityType.Create(this);
            var llmWikiEntrySourceRecord = LlmWikiEntrySourceRecordEntityType.Create(this);
            var llmWikiMcpTokenRecord = LlmWikiMcpTokenRecordEntityType.Create(this);
            var obsidianVaultClientRecord = ObsidianVaultClientRecordEntityType.Create(this);
            var obsidianVaultFileRecord = ObsidianVaultFileRecordEntityType.Create(this);
            var obsidianVaultFileVersionRecord = ObsidianVaultFileVersionRecordEntityType.Create(this);
            var obsidianVaultRecord = ObsidianVaultRecordEntityType.Create(this);
            var postRecord = PostRecordEntityType.Create(this);
            var postRevisionRecord = PostRevisionRecordEntityType.Create(this);
            var userRecord = UserRecordEntityType.Create(this);

            CommentRecordEntityType.CreateForeignKey1(commentRecord, postRecord);
            ExternalLoginRecordEntityType.CreateForeignKey1(externalLoginRecord, userRecord);
            FollowRecordEntityType.CreateForeignKey1(followRecord, userRecord);
            FollowRecordEntityType.CreateForeignKey2(followRecord, userRecord);
            LlmWikiEntryRecordEntityType.CreateForeignKey1(llmWikiEntryRecord, userRecord);
            LlmWikiEntrySourceRecordEntityType.CreateForeignKey1(llmWikiEntrySourceRecord, llmWikiEntryRecord);
            LlmWikiMcpTokenRecordEntityType.CreateForeignKey1(llmWikiMcpTokenRecord, userRecord);
            ObsidianVaultClientRecordEntityType.CreateForeignKey1(obsidianVaultClientRecord, userRecord);
            ObsidianVaultClientRecordEntityType.CreateForeignKey2(obsidianVaultClientRecord, obsidianVaultRecord);
            ObsidianVaultFileRecordEntityType.CreateForeignKey1(obsidianVaultFileRecord, userRecord);
            ObsidianVaultFileRecordEntityType.CreateForeignKey2(obsidianVaultFileRecord, obsidianVaultRecord);
            ObsidianVaultFileVersionRecordEntityType.CreateForeignKey1(obsidianVaultFileVersionRecord, userRecord);
            ObsidianVaultRecordEntityType.CreateForeignKey1(obsidianVaultRecord, userRecord);
            PostRevisionRecordEntityType.CreateForeignKey1(postRevisionRecord, postRecord);

            CommentRecordEntityType.CreateAnnotations(commentRecord);
            ExternalLoginRecordEntityType.CreateAnnotations(externalLoginRecord);
            FollowRecordEntityType.CreateAnnotations(followRecord);
            LlmWikiEntryRecordEntityType.CreateAnnotations(llmWikiEntryRecord);
            LlmWikiEntrySourceRecordEntityType.CreateAnnotations(llmWikiEntrySourceRecord);
            LlmWikiMcpTokenRecordEntityType.CreateAnnotations(llmWikiMcpTokenRecord);
            ObsidianVaultClientRecordEntityType.CreateAnnotations(obsidianVaultClientRecord);
            ObsidianVaultFileRecordEntityType.CreateAnnotations(obsidianVaultFileRecord);
            ObsidianVaultFileVersionRecordEntityType.CreateAnnotations(obsidianVaultFileVersionRecord);
            ObsidianVaultRecordEntityType.CreateAnnotations(obsidianVaultRecord);
            PostRecordEntityType.CreateAnnotations(postRecord);
            PostRevisionRecordEntityType.CreateAnnotations(postRevisionRecord);
            UserRecordEntityType.CreateAnnotations(userRecord);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "11.0.0-preview.4.26230.115");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
