// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Slogs.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class UserRecordEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Slogs.Data.UserRecord",
                typeof(UserRecord),
                baseEntityType,
                propertyCount: 6,
                keyCount: 1);

            var userName = runtimeEntityType.AddProperty(
                "UserName",
                typeof(string),
                propertyInfo: typeof(UserRecord).GetProperty("UserName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserRecord).GetField("<UserName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 80);
            userName.SetGetter(
                string (UserRecord instance) => UserRecordUnsafeAccessors.UserName(instance),
                bool (UserRecord instance) => UserRecordUnsafeAccessors.UserName(instance) == null);
            userName.SetSetter(
                UserRecord (UserRecord instance, string value) =>
                {
                    UserRecordUnsafeAccessors.UserName(instance) = value;
                    return instance;
                });
            userName.SetMaterializationSetter(
                UserRecord (UserRecord instance, string value) =>
                {
                    UserRecordUnsafeAccessors.UserName(instance) = value;
                    return instance;
                });
            userName.SetAccessors(
                string (IInternalEntry entry) => UserRecordUnsafeAccessors.UserName(((UserRecord)(entry.Entity))),
                string (IInternalEntry entry) => UserRecordUnsafeAccessors.UserName(((UserRecord)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(userName, 0),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(userName, 0));
            userName.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            userName.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "character varying(80)",
                    size: 80));
            userName.TypeMapping = ((NpgsqlStringTypeMapping)userName.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
        userName.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(userName));
        userName.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var bio = runtimeEntityType.AddProperty(
            "Bio",
            typeof(string),
            propertyInfo: typeof(UserRecord).GetProperty("Bio", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(UserRecord).GetField("<Bio>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            maxLength: 280);
        bio.SetGetter(
            string (UserRecord instance) => UserRecordUnsafeAccessors.Bio(instance),
            bool (UserRecord instance) => UserRecordUnsafeAccessors.Bio(instance) == null);
        bio.SetSetter(
            UserRecord (UserRecord instance, string value) =>
            {
                UserRecordUnsafeAccessors.Bio(instance) = value;
                return instance;
            });
        bio.SetMaterializationSetter(
            UserRecord (UserRecord instance, string value) =>
            {
                UserRecordUnsafeAccessors.Bio(instance) = value;
                return instance;
            });
        bio.SetAccessors(
            string (IInternalEntry entry) => UserRecordUnsafeAccessors.Bio(((UserRecord)(entry.Entity))),
            string (IInternalEntry entry) => UserRecordUnsafeAccessors.Bio(((UserRecord)(entry.Entity))),
            string (IInternalEntry entry) => entry.ReadOriginalValue<string>(bio, 1),
            string (IInternalEntry entry) => entry.GetCurrentValue<string>(bio));
        bio.SetPropertyIndexes(
            index: 1,
            originalValueIndex: 1,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        bio.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
            comparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            keyComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            providerValueComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "character varying(280)",
                size: 280));
        bio.TypeMapping = ((NpgsqlStringTypeMapping)bio.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
    bio.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var displayName = runtimeEntityType.AddProperty(
        "DisplayName",
        typeof(string),
        propertyInfo: typeof(UserRecord).GetProperty("DisplayName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(UserRecord).GetField("<DisplayName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        maxLength: 80);
    displayName.SetGetter(
        string (UserRecord instance) => UserRecordUnsafeAccessors.DisplayName(instance),
        bool (UserRecord instance) => UserRecordUnsafeAccessors.DisplayName(instance) == null);
    displayName.SetSetter(
        UserRecord (UserRecord instance, string value) =>
        {
            UserRecordUnsafeAccessors.DisplayName(instance) = value;
            return instance;
        });
    displayName.SetMaterializationSetter(
        UserRecord (UserRecord instance, string value) =>
        {
            UserRecordUnsafeAccessors.DisplayName(instance) = value;
            return instance;
        });
    displayName.SetAccessors(
        string (IInternalEntry entry) => UserRecordUnsafeAccessors.DisplayName(((UserRecord)(entry.Entity))),
        string (IInternalEntry entry) => UserRecordUnsafeAccessors.DisplayName(((UserRecord)(entry.Entity))),
        string (IInternalEntry entry) => entry.ReadOriginalValue<string>(displayName, 2),
        string (IInternalEntry entry) => entry.GetCurrentValue<string>(displayName));
    displayName.SetPropertyIndexes(
        index: 2,
        originalValueIndex: 2,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    displayName.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
        comparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        keyComparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        providerValueComparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        mappingInfo: new RelationalTypeMappingInfo(
            storeTypeName: "character varying(80)",
            size: 80));
    displayName.TypeMapping = ((NpgsqlStringTypeMapping)displayName.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
displayName.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var password = runtimeEntityType.AddProperty(
    "Password",
    typeof(string),
    propertyInfo: typeof(UserRecord).GetProperty("Password", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(UserRecord).GetField("<Password>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    maxLength: 200);
password.SetGetter(
    string (UserRecord instance) => UserRecordUnsafeAccessors.Password(instance),
    bool (UserRecord instance) => UserRecordUnsafeAccessors.Password(instance) == null);
password.SetSetter(
    UserRecord (UserRecord instance, string value) =>
    {
        UserRecordUnsafeAccessors.Password(instance) = value;
        return instance;
    });
password.SetMaterializationSetter(
    UserRecord (UserRecord instance, string value) =>
    {
        UserRecordUnsafeAccessors.Password(instance) = value;
        return instance;
    });
password.SetAccessors(
    string (IInternalEntry entry) => UserRecordUnsafeAccessors.Password(((UserRecord)(entry.Entity))),
    string (IInternalEntry entry) => UserRecordUnsafeAccessors.Password(((UserRecord)(entry.Entity))),
    string (IInternalEntry entry) => entry.ReadOriginalValue<string>(password, 3),
    string (IInternalEntry entry) => entry.GetCurrentValue<string>(password));
password.SetPropertyIndexes(
    index: 3,
    originalValueIndex: 3,
    shadowIndex: -1,
    relationshipIndex: -1,
    storeGenerationIndex: -1);
password.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
    comparer: new ValueComparer<string>(
        bool (string v1, string v2) => v1 == v2,
        int (string v) => ((object)v).GetHashCode(),
        string (string v) => v),
    keyComparer: new ValueComparer<string>(
        bool (string v1, string v2) => v1 == v2,
        int (string v) => ((object)v).GetHashCode(),
        string (string v) => v),
    providerValueComparer: new ValueComparer<string>(
        bool (string v1, string v2) => v1 == v2,
        int (string v) => ((object)v).GetHashCode(),
        string (string v) => v),
    mappingInfo: new RelationalTypeMappingInfo(
        storeTypeName: "character varying(200)",
        size: 200));
password.TypeMapping = ((NpgsqlStringTypeMapping)password.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
password.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var profileImageUrl = runtimeEntityType.AddProperty(
    "ProfileImageUrl",
    typeof(string),
    propertyInfo: typeof(UserRecord).GetProperty("ProfileImageUrl", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(UserRecord).GetField("<ProfileImageUrl>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    maxLength: 500);
profileImageUrl.SetGetter(
    string (UserRecord instance) => UserRecordUnsafeAccessors.ProfileImageUrl(instance),
    bool (UserRecord instance) => UserRecordUnsafeAccessors.ProfileImageUrl(instance) == null);
profileImageUrl.SetSetter(
    UserRecord (UserRecord instance, string value) =>
    {
        UserRecordUnsafeAccessors.ProfileImageUrl(instance) = value;
        return instance;
    });
profileImageUrl.SetMaterializationSetter(
    UserRecord (UserRecord instance, string value) =>
    {
        UserRecordUnsafeAccessors.ProfileImageUrl(instance) = value;
        return instance;
    });
profileImageUrl.SetAccessors(
    string (IInternalEntry entry) => UserRecordUnsafeAccessors.ProfileImageUrl(((UserRecord)(entry.Entity))),
    string (IInternalEntry entry) => UserRecordUnsafeAccessors.ProfileImageUrl(((UserRecord)(entry.Entity))),
    string (IInternalEntry entry) => entry.ReadOriginalValue<string>(profileImageUrl, 4),
    string (IInternalEntry entry) => entry.GetCurrentValue<string>(profileImageUrl));
profileImageUrl.SetPropertyIndexes(
    index: 4,
    originalValueIndex: 4,
    shadowIndex: -1,
    relationshipIndex: -1,
    storeGenerationIndex: -1);
profileImageUrl.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
    comparer: new ValueComparer<string>(
        bool (string v1, string v2) => v1 == v2,
        int (string v) => ((object)v).GetHashCode(),
        string (string v) => v),
    keyComparer: new ValueComparer<string>(
        bool (string v1, string v2) => v1 == v2,
        int (string v) => ((object)v).GetHashCode(),
        string (string v) => v),
    providerValueComparer: new ValueComparer<string>(
        bool (string v1, string v2) => v1 == v2,
        int (string v) => ((object)v).GetHashCode(),
        string (string v) => v),
    mappingInfo: new RelationalTypeMappingInfo(
        storeTypeName: "character varying(500)",
        size: 500));
profileImageUrl.TypeMapping = ((NpgsqlStringTypeMapping)profileImageUrl.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
profileImageUrl.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var registeredAt = runtimeEntityType.AddProperty(
    "RegisteredAt",
    typeof(DateTime),
    propertyInfo: typeof(UserRecord).GetProperty("RegisteredAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(UserRecord).GetField("<RegisteredAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
registeredAt.SetGetter(
    DateTime (UserRecord instance) => UserRecordUnsafeAccessors.RegisteredAt(instance),
    bool (UserRecord instance) => UserRecordUnsafeAccessors.RegisteredAt(instance) == default(DateTime));
registeredAt.SetSetter(
    UserRecord (UserRecord instance, DateTime value) =>
    {
        UserRecordUnsafeAccessors.RegisteredAt(instance) = value;
        return instance;
    });
registeredAt.SetMaterializationSetter(
    UserRecord (UserRecord instance, DateTime value) =>
    {
        UserRecordUnsafeAccessors.RegisteredAt(instance) = value;
        return instance;
    });
registeredAt.SetAccessors(
    DateTime (IInternalEntry entry) => UserRecordUnsafeAccessors.RegisteredAt(((UserRecord)(entry.Entity))),
    DateTime (IInternalEntry entry) => UserRecordUnsafeAccessors.RegisteredAt(((UserRecord)(entry.Entity))),
    DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(registeredAt, 5),
    DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(registeredAt));
registeredAt.SetPropertyIndexes(
    index: 5,
    originalValueIndex: 5,
    shadowIndex: -1,
    relationshipIndex: -1,
    storeGenerationIndex: -1);
registeredAt.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
    comparer: new ValueComparer<DateTime>(
        bool (DateTime v1, DateTime v2) => v1.Equals(v2),
        int (DateTime v) => ((object)v).GetHashCode(),
        DateTime (DateTime v) => v),
    keyComparer: new ValueComparer<DateTime>(
        bool (DateTime v1, DateTime v2) => v1.Equals(v2),
        int (DateTime v) => ((object)v).GetHashCode(),
        DateTime (DateTime v) => v),
    providerValueComparer: new ValueComparer<DateTime>(
        bool (DateTime v1, DateTime v2) => v1.Equals(v2),
        int (DateTime v) => ((object)v).GetHashCode(),
        DateTime (DateTime v) => v));
registeredAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var key = runtimeEntityType.AddKey(
    new[] { userName });
runtimeEntityType.SetPrimaryKey(key);

return runtimeEntityType;
}

public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
{
    var userName = runtimeEntityType.FindProperty("UserName");
    var bio = runtimeEntityType.FindProperty("Bio");
    var displayName = runtimeEntityType.FindProperty("DisplayName");
    var password = runtimeEntityType.FindProperty("Password");
    var profileImageUrl = runtimeEntityType.FindProperty("ProfileImageUrl");
    var registeredAt = runtimeEntityType.FindProperty("RegisteredAt");
    var key = runtimeEntityType.FindKey(new[] { userName });
    key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNullableFactory<string, int>(key));
    key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<string>(key));
    runtimeEntityType.SetOriginalValuesFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((UserRecord)(source.Entity));
            return ((ISnapshot)(new Snapshot<string, string, string, string, string, DateTime>((source.GetCurrentValue<string>(userName) == null ? null : ((ValueComparer<string>)(((IProperty)userName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(userName))), (source.GetCurrentValue<string>(bio) == null ? null : ((ValueComparer<string>)(((IProperty)bio).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(bio))), (source.GetCurrentValue<string>(displayName) == null ? null : ((ValueComparer<string>)(((IProperty)displayName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(displayName))), (source.GetCurrentValue<string>(password) == null ? null : ((ValueComparer<string>)(((IProperty)password).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(password))), (source.GetCurrentValue<string>(profileImageUrl) == null ? null : ((ValueComparer<string>)(((IProperty)profileImageUrl).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(profileImageUrl))), ((ValueComparer<DateTime>)(((IProperty)registeredAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(registeredAt)))));
        });
    runtimeEntityType.SetStoreGeneratedValuesFactory(
        ISnapshot () => Snapshot.Empty);
    runtimeEntityType.SetTemporaryValuesFactory(
        ISnapshot (IInternalEntry source) => Snapshot.Empty);
    runtimeEntityType.SetShadowValuesFactory(
        ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
    runtimeEntityType.SetEmptyShadowValuesFactory(
        ISnapshot () => Snapshot.Empty);
    runtimeEntityType.SetRelationshipSnapshotFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((UserRecord)(source.Entity));
            return ((ISnapshot)(new Snapshot<string>((source.GetCurrentValue<string>(userName) == null ? null : ((ValueComparer<string>)(((IProperty)userName).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(userName))))));
        });
    runtimeEntityType.SetCounts(new PropertyCounts(
        propertyCount: 6,
        navigationCount: 0,
        complexPropertyCount: 0,
        complexCollectionCount: 0,
        originalValueCount: 6,
        shadowCount: 0,
        relationshipCount: 1,
        storeGeneratedCount: 0));
    runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
    runtimeEntityType.AddAnnotation("Relational:Schema", null);
    runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
    runtimeEntityType.AddAnnotation("Relational:TableName", "Users");
    runtimeEntityType.AddAnnotation("Relational:ViewName", null);
    runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

    Customize(runtimeEntityType);
}

static partial void Customize(RuntimeEntityType runtimeEntityType);
}
}
