// <auto-generated />
using System;
using System.Runtime.CompilerServices;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Slogs.Data.CompiledModels
{
    public static class UserRecordUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserName>k__BackingField")]
        public static extern ref string UserName(UserRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Bio>k__BackingField")]
        public static extern ref string Bio(UserRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DisplayName>k__BackingField")]
        public static extern ref string DisplayName(UserRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Password>k__BackingField")]
        public static extern ref string Password(UserRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProfileImageUrl>k__BackingField")]
        public static extern ref string ProfileImageUrl(UserRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RegisteredAt>k__BackingField")]
        public static extern ref DateTime RegisteredAt(UserRecord @this);
    }
}
